### PR TITLE
Update to pylint 1.0 and python 3.3

### PR DESCRIPTION
**Pull request by ziggr**
I needed a pylint checker to flag all our not-yet-gettext()ed strings, and python-pylint-i18n worked like a champ. Thanks for writing it.

These commits are the updates to deal with more library name changes, and Python 3.3.

### CODE REVIEW

**Comment by amandasaurus** [comment]
Oh interesting. I'll look at this over the next few days. Nice to see py3 support. That's something I need to get better at.

re: the _is_str(), In py2 you can use basestr as a class that str and unicode subclass (which I became aware of after writing this). I wonder if that might work here?

**Comment by meshy** [comment]
@rory Thanks for this library!
@ziggr Thanks for this patch, my project uses python 3, too. `:)`

@rory Bytestrings and unicode strings in python 3 do not share `basestr` as a common base. The [way six deals with this](https://github.com/kelp404/six/blob/master/six.py#L24-L44) more-or-less boils down to:

```
import sys
if sys.version_info[0] == 3:
    string_types = (str,)
else:
    string_types = (basestring,)
```

This allows us to then check `isinstance(node.value, string_types)`. (Note that the [second argument of `isinstance` can be a tuple](https://docs.python.org/3/library/functions.html#isinstance).)

Would that be more to your liking?

**Comment by meshy** [comment]
Looking at my code there, I suppose it doesn't really matter that the second arg is a tuple. Oh well `:)`

**Comment by amandasaurus** [comment]
welp, i forgot to look at this.. sorry. will do later

**Comment by meshy** [comment]
Fantastic! Would it be possible to make a new release to PyPI?

**Comment by amandasaurus** [comment]
Just did a version bump to 1.0.0 ( https://pypi.python.org/pypi/pylint-i18n ). I'm going to start following semver.org version numbering. It includes your changes.

**Comment by meshy** [comment]
Thank you very much `:)`

**Pull request merged**
